# Generated by Django 2.0.3 on 2018-03-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdata',
            name='expkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PName', to='core.PhageData'),
        ),
        migrations.AlterField(
            model_name='isolationdata',
            name='isokey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='iso_phageName', to='core.PhageData'),
        ),
        migrations.AlterField(
            model_name='predata',
            name='testkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PhageName', to='core.PhageData'),
        ),
    ]
